@startuml
usecase (gérer compte) as UC_Gerer_Compte
usecase (gérer compte utilisateur) as UC_Gerer_Compte_Utilisateur
usecase (gérer catalogueue) as UC_Gerer_catalogueue
usecase (gérer Entreprise cliente) as UC_Gerer_Entreprise
usecase (gérer commande) as UC_Gerer_Commande
usecase (gérer personnes apte) as UC_Gerer_personnes_apte
usecase (consulter informations) as UC_Consulter_informationss
usecase (consulter catalogueue) as UC_Consulter_catalogue
usecase (consulter panier) as UC_Panier
usecase (Modifier mon mot de passe) as UC_MDP
usecase (gérer produit) as UC_G_Produit
usecase (gérer catégorie produit) as UC_G_Cat_Produit
usecase (gérer Consulter Commande) as UC_Consulter_Commande






actor :administrateur du logiciel: as admin
actor :Rédacteur: as Rédacteur
actor :Entreprise cliente: as Entreprise
actor :salarié Entreprise cliente: as Salarie
actor :Commercial: as Commercial




admin --> UC_Gerer_Compte
admin --> UC_Gerer_Compte_Utilisateur







Salarie --> UC_Consulter_catalogue
Salarie --> UC_Gerer_Compte
Salarie --> UC_Panier
Salarie --> UC_Consulter_Commande


Rédacteur --> UC_Gerer_Compte
Rédacteur --> UC_Gerer_catalogueue

Commercial --> UC_Gerer_Compte
Commercial --> UC_Gerer_Entreprise
Commercial --> UC_Gerer_Commande


Entreprise --> UC_Gerer_Compte
Entreprise --> UC_Gerer_personnes_apte
Entreprise --> UC_Consulter_informationss





UC_Gerer_Compte --> UC_MDP
UC_Gerer_catalogueue --> UC_G_Produit
UC_Gerer_catalogueue --> UC_G_Cat_Produit


@enduml



