@startuml

usecase (gérer compte) as UC_Gerer_Compte
usecase (gérer compte utilisateur) as UC_Gerer_Compte_Utilisateur
usecase (gérer catalogue) as UC_Gerer_Catalogue
usecase (gérer entreprise cliente) as UC_Gerer_Entreprise
usecase (gérer commande) as UC_Gerer_Commande
usecase (gérer personnes habilités) as UC_Gerer_personnes_habilités
usecase (consulter info) as UC_Consulter_infos
usecase (consulter catalogue) as UC_Consulter_catalog
usecase (consulter panier) as UC_Panier
usecase (Modifier mon mot de passe) as UC_MDP
usecase (gérer produit) as UC_G_Produit
usecase (gérer catégorie produit) as UC_G_Cat_Produit
usecase (gérer Consulter Commande) as UC_Consulter_Commande



actor :administrateur du logiciel: as admin
actor :utilisateur Cafe: as userCafe
actor :entreprise cliente: as entreprise
actor :salarié entreprise cliente: as salarie


admin --> UC_Gerer_Compte
admin --> UC_Gerer_Catalogue
admin --> UC_Gerer_Entreprise
admin --> UC_Gerer_Commande
admin --> UC_Gerer_Compte_Utilisateur


userCafe --> UC_Gerer_Compte
userCafe --> UC_Gerer_Catalogue
userCafe --> UC_Gerer_Entreprise
userCafe --> UC_Gerer_Commande
userCafe --> UC_Gerer_Compte_Utilisateur

entreprise --> UC_Gerer_Compte
entreprise --> UC_Gerer_personnes_habilités
entreprise --> UC_Consulter_infos

salarie --> UC_Consulter_catalog
salarie --> UC_Gerer_Compte
salarie --> UC_Panier
salarie --> UC_Consulter_Commande

UC_Gerer_Compte --> UC_MDP
UC_Gerer_Catalogue --> UC_G_Produit
UC_Gerer_Catalogue --> UC_G_Cat_Produit

@enduml

